### ISSUE TITLE
Unable to install the plugin. 

### ISSUE THREAD

**Issue by ramsabarish** [whiteoctober/cordova-plugin-app-version#76]
I'm unable to install the plugin, it fails with the error 'Object has no method parse'. My cordova project only contains android platform so I can't say about iOS. Kindly guide me to install this plugin.
Cordova Version: 6.0.0.
Android Studios SDK version: 23. 
![screen shot 2016-03-02 at 7 45 15 pm](https://cloud.githubusercontent.com/assets/10074524/13463844/30d6068a-e0b4-11e5-8585-2d7c1084995c.png)

**Comment by richsage** [comment]
What version of node are you using?

**Comment by ramsabarish** [comment]
Sorry for late. The node version is v0.10.35.

**Comment by richsage** [comment]
Ah - this is a bug in Cordova, which didn't work with node 0.10.x at one point - see [the issue here](https://issues.apache.org/jira/browse/CB-9981) and similar Cordova plugin report [here](https://github.com/apla/me.apla.cordova.app-preferences/issues/63) too. However you say you're on Cordova 6.0.0 (which should have had that patch applied)?

**Comment by Maikell84** [comment]
I have exactly the same issue:

cordova -v
`6.0.0`

node -v
`v0.10.42`

npm -v
`2.14.19`

best regards

**Comment by levinse** [comment]
We're having the same issue since switching from meteor 1.2 to meteor 1.3

**Comment by StijnAvdL** [comment]
Also problem with meteor 1.3.2.4 
+1

**Comment by mnewmedia** [comment]
no problems with `cordova-plugin-appinfo`

**Comment by Drarok** [comment]
As this seems to be related to very old versions of Node, and I've just successfully installed the plugin using LTS versions, I'm going to close it.
