### ISSUE TITLE
Browser platform not working

### ISSUE THREAD

**Issue by Hexodus** [whiteoctober/cordova-plugin-app-version#86]
I installed the plugin correctly and got the desired result on Android but not in the browser version. 

When I run the following code:

     cordova.getAppVersion.getVersionNumber(function (version) {
          alert(version);
         });

This trows the error:

    Error: exec proxy not found for :: AppVersion :: getVersionNumber

Am I doing something wrong or isn't really working with the browser platform?

**Comment by jvjvjv** [comment]
Browser platform is not supported, it appears. iOS, Android, Windows are the only supported platforms.

**Comment by nikmartin** [comment]
What version would you expect this plugin to return in a browser?

**Comment by mgkimsal** [comment]
I'd expect the version number that would appear on any other platform.  My version number is a string from config.xml, correct?

**Comment by nikmartin** [comment]
@mgkimsal @Hexodus this plugin extracts the version from the compiled executable using the native platform API, so it won't work in the browser. config.xml is not read at runtime, it's read and compiled in to the native platform binaries

**Comment by jgfet** [comment]
I'd have expected it could have come from ionic.config.json or package.json personally too. But now I know..

**Comment by ThorvaldAagaard** [comment]
Would it be difficult to add the browser platform to this plugin?

**Comment by Drarok** [comment]
The browser platform is not currently supported, this is aimed at iOS, Android, and Windows apps.

**Comment by ThorvaldAagaard** [comment]
Is it difficult to support browser?

**Comment by Drarok** [comment]
I can't see _any_ asset that's included in the browser build by default that includes the version number, so I don't think it's possible without some custom build steps or assets?

**Comment by ThorvaldAagaard** [comment]
You are right.

Until now I have solved it by adding a variable to my solution, so in my main.js I can find

this.version = "0.4.0";

and then I have to use that instead of the plugin.

But you are right, it will require either a custom change in the build process, or probably a better solution that the Ionic team adds the version during build to the browser-platform, somewhere you can pick it up.

But also Ionic claims that the browser platform is just experimental and not intended for production, so it seems I will have to continue to update the version in both my solution and in the config.xml.

and thanks for taking the time to take another look into this

best regards
Thorvald

**Comment by Drarok** [comment]
Hmm, I should have looked at the Pull Requests before the issues…

There's an [outstanding PR](https://github.com/whiteoctober/cordova-plugin-app-version/pull/84) that offers browser support, though I've not tested that yet. Might be worth looking at, see if it solves your issue?

I've run out of time for today, but I'll be back soon to tidy up this plugin.

**Comment by ThorvaldAagaard** [comment]
As far as I can see he is reading config.xml (In AppVersionProxy), but that is not part of the browser distribution, but I will see if I can get it tested on the broser platform (when uploaded to firebase)

**Comment by gerhardcit** [comment]
@Drarok , can you at least try and catch an error so that it does not break when using is in a cordova browser mode?
