### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by R1Daneel** [whiteoctober/cordova-plugin-app-version#89]
I'd like to know if this project is still supported.

**Comment by MathieuLopes** [comment]
Same question...

**Comment by nikmartin** [comment]
Do you have an issue? The API that this plugin uses has been around since Android API level 1, so this project will likely not change much. It will probably break if the Cordova API changes.

**Comment by am** [comment]
@nikmartin I think the issue is to find a project that has many Pull Resquest opened for a long time and without resolution. And the same applies for issues. I understand the problem could be lack of time to mantain the project, but if that is the case maybe it would be nice to add a note in the readme that the project is no longer mantained, and maybe add the possibility elect someone to mantain the project.

**Comment by Drarok** [comment]
@am you're right – that would be nice! I'll hopefully have some time tomorrow to take a look at tidying up the project, and adding a request for maintainer(s) to the README, since we don't really work on Cordova-based apps much these days.

**Comment by DennisSmolek** [comment]
Hey All, I've been added as a maintainer and will be going through open issues/pull requests to bring things up to date and then work on some slight revisions in the core readme. 

We use this for Windows, Android, and iOS so it's something we want to try and keep up and running. So far we are on all latest cordova builds and versions and seems solid.

I don't have any big plans feature wise but am open to them if you think something important, just add the `feature request` tag
