### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by pbangsoe** [whiteoctober/cordova-plugin-app-version#94]
Getting following error on install

Any suggestions ?

Error: Failed to fetch plugin git+https://github.com/whiteoctober/cordova-plugin-app-version.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by stevesum** [comment]
This problem is probably because you use cordova 7. Try use the --nofetch
option to get the previous behaviour of the cordova.

cordova plugin add {plugin-name} --nofetch

The cordova 7 uses the npm to install the plugins, and probably your npm is
not globally installed, or misconfigured.

2017-07-22 18:58 GMT+02:00 pbangsoe <notifications@github.com>:

**Comment by Himanshu-BAZ** [comment]
Please help on this, having the same issue.

**Comment by pbangsoe** [comment]
@Himanshu-BAZ 
stevesums solution worked for me together  with an "plugin reset" as follows

from project dir..

cordova plugins --save
cordova platforms --save
rm -rf platforms
rm -rf plugins
cordova prepare

**Comment by Drarok** [comment]
Looks like you've managed to solve your problem? 🙂
